### ISSUE TITLE
Can't use npm scripts with colon or underscore in the names?

### ISSUE THREAD

**Issue by mikesnare** [srs/gradle-node-plugin#183] opened 2017-01-04 14:42 UTC
A section of my package.json's script blocks looks like this:

```json
    "build": "npm run build:dev",
    "build:dev": "npm run lessc && npm run tsc",
    "build:prod": "npm run lessc && npm run tsc && npm run gulp:bundle",
    "gulp:bundle": "node --max-old-space-size=2048 node_modules/gulp/bin/gulp bundle",
```

In my build.gradle, I'd like to run the build:prod script.  I initially tried this:

```groovy
task webBuild(dependsOn: [npmInstall, 'npm_run_build:prod'])

war {
    dependsOn webBuild
}
```

But the error is 

> Could not determine the dependencies of task 'webapp:webBuild'.
> Task with path 'npm_run_build:prod' not found in project 'webapp'.

So I went into my package.json and tried replacing all the colons (:) with underscores (_) as follows:

```json
    "build": "npm run build_dev",
    "build_dev": "npm run lessc && npm run tsc",
    "build_prod": "npm run lessc && npm run tsc && npm run gulp_bundle",
    "gulp_bundle": "node --max-old-space-size=2048 node_modules/gulp/bin/gulp bundle",
```

and then updating my build.gradle (which is better for the dependency setup anyway:)

```groovy
task npm_run_build_prod {
    dependsOn npmInstall
}

task webBuild(dependsOn: npm_run_build_prod)

war {
    dependsOn webBuild
}
```

but it seems that the pattern recognition for dynamic tasks splits on all the underscores.  So instead of invoking, say, `build_prod` as I'd hoped, gradle is invoking the `build` script with an argument of `prod` which causes the build to puke.

What are the options here (besides renaming to `buildprod`)?

**Comment by mikesnare** [comment] 2017-01-04 14:49
Ok, yeah.  https://github.com/srs/gradle-node-plugin/blob/master/src/main/groovy/com/moowork/gradle/node/NodePlugin.groovy#L74

It's just splitting on underscores.  I see why this is happening now.  I guess for now I have to create a custom task for this.  Bummer.

**Comment by srs** [comment] 2017-01-05 22:22
We could probably split both on _ (underscore) and : (colon).

**Comment by mikesnare** [comment] 2017-01-09 14:49
It might make sense to detect special cases (like run or install) by splitting on something like `_run_` or `_install_` instead of splitting on underscore?  The second value in the resulting array could then just be passed without manipulation.

**Comment by mikesnare** [comment] 2017-01-09 14:51
Regardless, I was able to move past this using the following (in case anyone else ever runs into this and finds this thread):

```groovy
task webBuild(type: NpmTask, dependsOn: npmInstall) {
    args = ['run', 'build:dev']
}
```

So feel free to close this issue unless you consider it a bug.  Thanks.

**Comment by srs** [comment] 2017-01-13 08:50
Great that you was able to move past this. Closing this issue. Not a bug ;-)

**Closed by srs** 2017-01-13 08:50 UTC

**Comment by andys8** [comment] 2017-01-23 13:45
@srs I had the same problem and I'm glad I could use the same solution. Because colons are quiten often used in npm script names, I'd prefer to have this documented. But it would be awesome, if it would work out of the box. I would expect using `npm_run_build_dev` or `npm_run_build:dev` :)

**Comment by IllusionMH** [comment] 2017-02-14 16:02
Same problem here. `gradle-node-plugin` is usually used to avoid global installations of Node.js for back-end developers and ensuring same node version for all developers, therefore all manuals and tasks that are supposed to run in CLI use `npm_run_task-name`.

It will be nice to see support for `:` in script names as enhancement.
