### ISSUE TITLE
Symlinks for npm not established npm -> ../lib/node_modules/npm/bin/npm-cli.js

### ISSUE THREAD

**Issue by minibuta** [srs/gradle-node-plugin#181] opened 2017-01-03 04:32 UTC
For some reason the local npm symlink in .gradle/nodejs/node-v6.4.0-XXX-x64/bin folder hasn't been established when running npm_install
Tried it under both linux and mac.

should be npm -> ../lib/node_modules/npm/bin/npm-cli.js
but instead its a zero sized file.

Here is a sample gradle file to reproduce.

```group 'npmtest'
version '1.0-SNAPSHOT'

buildscript {
    ext {
    }
    repositories {
        mavenCentral()
        jcenter()
        maven { url "https://plugins.gradle.org/m2/" }
    }
    dependencies {
        classpath "com.moowork.gradle:gradle-node-plugin:1.0.1"
    }
}

apply plugin: 'com.moowork.node'

node {
    version = "6.4.0"
    download = true
}

task nodeInstall(type: NodeTask) {
}
```

**Comment by nhoughto** [comment] 2017-01-04 06:13
Seems to be a duplicate of
https://github.com/srs/gradle-node-plugin/issues/164

**Comment by srs** [comment] 2017-01-13 08:44
Fixed in master. Closing this issue.

**Closed by srs** 2017-01-13 08:44 UTC
