### ISSUE TITLE
Add Npm to 'Path' of NodeTask

### ISSUE THREAD

**Issue by cdietrich** [srs/gradle-node-plugin#134] opened 2016-08-11 18:33 UTC
Running on a machine with no node/npm installed

When i execute a NodeTask calling a Module that calls Npm via exec then it wont find npm / use the destroyed symlink extracted. thus it would be nice if this would work out of the box instead of using

```
task npmInstallNpm(type: NpmTask, dependsOn: npmSetup) {
    group 'Node'
    description 'Installs NPM"'
    args = [ 'install', '-g', 'npm' ]
}
```

here is what the node module `vsce` does (one of may npm calls)

```
require('child_process').exec('npm -v' ....)
```

**Comment by Hildebrand** [comment] 2016-11-10 08:14
This is indeed an issue. The yeoman doctor (part of the yo NPM package) also does a version check that fails if being ran from the gradle-node locally installed Node. To be precise, it's this file: https://github.com/yeoman/doctor/blob/master/lib/rules/npm-version.js failing to find npm.

as I have npm installed globally already I wonder if @cdietrich solution will help..

**Comment by cbornet** [comment] 2016-12-12 22:06
:+1: I also have the yo package installation failure.

**Comment by cbornet** [comment] 2016-12-12 23:02
To reproduce very easily:
```
./gradlew npm_install_yo
```

**Comment by cbornet** [comment] 2016-12-14 18:14
Looks like the same issue as #146 introduced by yarn support in 0.14
Downgrading to 0.13 fixes it (but you lose yarn support :disappointed: )

**Comment by s0x** [comment] 2016-12-14 20:17
This is related to #164 and would be fixed by MR #165

**Closed** 2017-01-13 08:44 UTC
